version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: finstore_postgres
    environment:
      POSTGRES_USER: ${MY_POSTGRES_USER}
      POSTGRES_PASSWORD: ${MY_POSTGRES_PASSWORD}
      POSTGRES_DB: ${MY_POSTGRES_DB}
    volumes:
      - /Users/zhengshuang/Documents/Datacenter/FinStore/Postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
